#!/usr/bin/env bash
# shellcheck disable=SC2181

function echo() {
    command echo -e "${@}"
}

function help_menu() {
    echo
    echo "${BOLD}SWAP MANAGER${RST}"
    echo
    echo "${BOLD}USAGE:${RST} ${0} <options>"
    echo
    echo "${BOLD}EXAMPLE:${RST} ${0} -a"
    echo
    echo "${BOLD}EXAMPLE:${RST} ${0} --add"
    echo
    echo " -a | --add:        Add Swap"
    echo " -c | --check:      Check swap"
    echo " -d | --disable:    Disable swap"
    echo " -e | --enable:     Enable swap"
    echo " -h | --help:       Help menu"
    echo " -r | --replace:    Replace current swap"
    echo
}

function setup_variables() {
    BOLD="\033[1m"
    RST="\033[0m"
}

function enable() {
    echo
    sudo swapon /swapfile
}

function disable() {
    echo
    sudo swapoff /swapfile
}

function custom_swap() {
    read -r -p "Do you want change swap size? [y/N]" PROMPT
    if [[ $PROMPT =~ [yY](es)* ]]; then
       echo "Enter swap size : "
       read -r SIZE
    fi
}

function addswap() {
    custom_swap
    grep -q "swapfile" /etc/fstab
    if [[ $? -ne 0 ]]; then
       echo "swapfile not found. Adding swapfile."
       if [[ -z $SIZE ]]; then
          echo
          echo "Add 1G swap"
          sudo fallocate -l 1G /swapfile
       else
          echo
          echo "Add ${SIZE}G swap"
          sudo fallocate -l "${SIZE}"G /swapfile
       fi
       sudo chmod 600 /swapfile
       sudo mkswap /swapfile
       sudo swapon /swapfile
       sudo cp /etc/fstab /etc/fstab.bak
       echo "/swapfile none swap sw 0 0" >> /etc/fstab
       tuning_swap
    else
       overwrite_swap
    fi
}

function overwrite_swap() {
    read -r -p "do you want replace current swap? [y/N]" PROMPT
    if [[ $PROMPT =~ [yY](es)* ]]; then
       sudo swapoff /swapfile
       if [[ -z $SIZE ]]; then
          echo
          echo "overwrite swap to 1G"
          sudo fallocate -l 1G /swapfile
       else
          echo
          echo "overwrite swap to ${SIZE}G"
          sudo fallocate -l "${SIZE}"G /swapfile
       fi
       sudo mkswap /swapfile
       sudo swapon /swapfile
    fi
}

function replace_swap() {
    read -r -p "do you want replace current swap? [y/N]" PROMPT
    if [[ $PROMPT =~ [yY](es)* ]]; then
       echo "current swap will be replace to 1G or"
       custom_swap
       sudo swapoff /swapfile
       if [[ -z $SIZE ]]; then
          echo
          echo "overwrite swap to 1G"
          sudo fallocate -l 1G /swapfile
       else
          echo
          echo "overwrite swap to ${SIZE}G"
          sudo fallocate -l "${SIZE}"G /swapfile
       fi
       sudo mkswap /swapfile
       sudo swapon /swapfile
    fi
}

function result() {
    echo
    < /proc/meminfo grep Swap
    echo
}

function tuning_swap() {
    echo
    echo "tuning swap"
    sudo sysctl vm.swappiness=30
    echo "vm.swappiness=30" >> /etc/sysctl.conf
    sudo sysctl vm.vfs_cache_pressure=50
    echo "vm.vfs_cache_pressure=50" >> /etc/sysctl.conf
    echo
}

function parameters() {
    case "${1}" in
        "-a"|"--add") addswap ;;
        "-c"|"--check") result ;;
        "-d"|"--disable") disable ;;
        "-e"|"--enable") enable ;;
        "-r"|"--replace") replace_swap ;;
        "-h"|"--help"|*) help_menu ;;
    esac
}

setup_variables
parameters "${@}"
